using UnityEngine;
using System.Collections;
using DinoFracture;

namespace ThousandFloors
{
    /// <summary>
    /// Attached to the Fracture Root object. 
    /// Manages the lifetime and shrinking of all child shards.
    /// </summary>
    public class ShardController : MonoBehaviour
    {
        public float lifetime = 1.0f;
        public float shrinkDuration = 0.3f;

        private void Start()
        {
            // Find all actual shards generated by DinoFracture
            FracturedObject[] shards = GetComponentsInChildren<FracturedObject>();
            
            foreach (var shard in shards)
            {
                StartCoroutine(ShrinkAndVanish(shard.transform));
            }

            // Destroy the entire root container after the shards have finished shrinking
            Destroy(gameObject, lifetime + shrinkDuration + 0.1f);
        }

        private IEnumerator ShrinkAndVanish(Transform shardTransform)
        {
            yield return new WaitForSeconds(lifetime);

            float elapsed = 0;
            Vector3 startScale = shardTransform.localScale;

            while (elapsed < shrinkDuration)
            {
                shardTransform.localScale = Vector3.Lerp(startScale, Vector3.zero, elapsed / shrinkDuration);
                elapsed += Time.deltaTime;
                yield return null;
            }

            shardTransform.localScale = Vector3.zero;
        }
    }
}